name: bloc_router_generator
description: Bloc Route Generator.
version: 0.0.1
homepage: https://github.com/OnixFlutterTeam/bloc_router_generator

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^2.1.5
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4

flutter:

  plugin:
    platforms:
      android:
        package: com.bloc.router.gen.bloc_router_generator
        pluginClass: BlocRouterGeneratorPlugin
      ios:
        pluginClass: BlocRouterGeneratorPlugin

