name: bloc_router_generator
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  build:
  source_gen:

dev_dependencies:
  build_test:
  build_runner:
  test: ^1.21.1
  flutter_lints: ^1.0.4

flutter:

  plugin:
    platforms:
      android:
        package: com.bloc.router.gen.bloc_router_generator
        pluginClass: BlocRouterGeneratorPlugin
      ios:
        pluginClass: BlocRouterGeneratorPlugin

