name: bloc_router_generator
description: Bloc Route Generator.
version: 0.0.3
homepage: https://github.com/OnixFlutterTeam/bloc_router_generator

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.0.0
  source_gen: ^1.2.0
  analyzer: ">=3.0.0 <5.0.0"

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  test: ^1.20.1
  source_gen_test: ^1.0.2

flutter:

  plugin:
    platforms:
      android:
        package: com.bloc.router.gen.bloc_router_generator
        pluginClass: BlocRouterGeneratorPlugin
      ios:
        pluginClass: BlocRouterGeneratorPlugin

